version: '3.8'


services:
  user:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: user

    working_dir : /app
    command : python3 user_service.py
    volumes: 
      - ./services/user_service.py:/app/user_service.py
    ports:
      - "5001:5010"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=user_service.py
    networks:
      - microservices-network
    restart: unless-stopped

  
  product:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: product

    working_dir : /app
    command : python3 product_service.py
    volumes: 
      - ./services/product_service.py:/app/product_service.py
    ports:
      - "5002:5010"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=product_service.py
    networks:
      - microservices-network
    restart: unless-stopped

  
  order:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: order

    working_dir : /app
    command : python3 order_service.py
    volumes: 
      - ./services/order_service.py:/app/order_service.py
    ports:
      - "5003:5010"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=order_service.py
    networks:
      - microservices-network
    restart: unless-stopped


networks:
  microservices-network:
    driver: bridge


