version: '3.8'


services:
  user:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: user

    working_dir : /app
    command: flask --app user_service run --host=0.0.0.0 --port=5010 --debug
    volumes: 
      - ./services:/app
      - ./data:/data
    ports:
      - "5001:5010"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=user_service.py
    networks:
      - microservices-network
    restart: unless-stopped

  
  product:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: product

    working_dir : /app
    command: flask --app product_service run --host=0.0.0.0 --port=5010 --debug
    volumes: 
      - ./services:/app
      - ./data:/data
    ports:
      - "5002:5010"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=product_service.py
    networks:
      - microservices-network
    restart: unless-stopped

  
  order:
    build:
      context: .
      dockerfile: services/Dockerfile.services

    container_name: order

    working_dir : /app
    command: flask --app order_service run --host=0.0.0.0 --port=5010 --debug
    volumes: 
      - ./services:/app
      - ./data:/data
    ports:
      - "5003:5010"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=order_service.py
    networks:
      - microservices-network
    restart: unless-stopped


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    working_dir : /app
    command: flask --app app run --host=0.0.0.0 --port=5010 --debug
    volumes:
      - ./app:/app
    ports:
      - "8080:5010"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - user
      - product
      - order
    networks:
      - microservices-network
    restart: unless-stopped


networks:
  microservices-network:
    driver: bridge


